### ISSUE TITLE
### 06/01/2020 SQL

### ISSUE THREAD

**Issue by JakeHamiltonVGT** [HarryB96/SpartanTrainingRoom#1]
Getting the columns all ready for use in the MVC. Hosted on Azure.

**Comment by JakeHamiltonVGT** [comment]
Things to discuss:
Password encryption
Deadline being nullable?
Course/Questions table?

For now, we have no encryption. 
Deadline is set to nullable.
We have no reference of Course or Question as of right now.

**Comment by HarryB96** [comment]
Add ADO.Net model to project
